services:
  toxictypo_app:
    image: toxictypoapp:1.0-SNAPSHOT
    # image: toxictypo_app
    container_name: toxictypo_app
    networks:
      - toxictypo_testing_network
    ports:
      - "8085:8080"

  toxictypo_tests:
    image: toxictypo_tests
    container_name: toxictypo_tests
    # depends_on:
    #   - toxictypo_app
    networks:
      - toxictypo_testing_network

networks:
  toxictypo_testing_network:
    driver: bridge