FROM maven:3.8.4-jdk-8 AS build
WORKDIR /app
COPY pom.xml /app
COPY src /app/src
RUN mvn clean package -U --batch-mode -Dmaven.test.skip=true

FROM eclipse-temurin:8u412-b08-jre-alpine
COPY --from=build /app /app
WORKDIR /app
EXPOSE 8085

ENTRYPOINT ["java", "-jar", "/app/target/toxictypoapp-1.0-SNAPSHOT.jar"]